baseurl = "https://blake417.github.io"
languageCode = "en-us"
title = "Blake Larson"
theme = "hugo-creative-theme"
googleAnalytics = ""
# Hello
[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Blake Larson"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Blake Larson"

		[params.navigation.links]
			about     = "About"
			services  = "Media"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Blake Larson"
		subtitle   = "The noblest pleasure is the joy of understanding."
		buttonText = "Welcome!"


	# About section
	[params.about]
		headline    = "A little about me."
		description = "TODO"
		buttonText  = "Back to top!"


	# Service section
	[params.services]
		headline = "Visit my Media!"

        [[params.services.list]]
            icon = "fa-github"
			title = "Github"
            link = "https://github.com/blake417"

        [[params.services.list]]
			icon = "fa-linkedin-square"
			#text = "LinkedIn"
			title = "LinkedIn"
			link = "https://www.linkedin.com/in/blake-d-larson/"

		[[params.services.list]]
            icon = "fa-youtube"
            title = "Youtube"
			link = "https://www.youtube.com/channel/UCI6rN_jlvkXZqYEoo8aXFGA"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Check out my services!"

		[params.aside.button]
			text = "TODO Headline"
			link = ""

		#[params.aside.button]
			#text = "Visit my LinkedIn!"
			#link = "https://www.linkedin.com/in/blake-d-larson/"


	# Contact section
	[params.contact]
		headline = "Questions or Inquires?"
		description = "TODO"
		phone = "(253) 370-1686"
		email = "blake7@hawaii.edu"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
